var levelDict = [
              {
                id:"1000",
                text:"安徽省",
                childs:[
                         {
                            id:"1001",
                            text:"合肥市",
                            childs:[
                                      {
                                        id:"100100",
                                        text:"蜀山区"
                                       },
                                       {
                                         id:"100101",
                                         text:"包河区"
                                        }
                                    ]      
                          },
                          {
                            id:"1002",
                            text:"六安市",
                            childs:[
                                        {
                                            id:"100200",
                                            text:"金安区"
                                        },
                                        {
                                            id:"100201",
                                            text:"裕安区"
                                        }
                                  ]
                          }
                        ]      
                },
                {   
                    id:"2000",
                    text:"河北省",
                    childs:[
                             {
                                id:"2001",
                                text:"石家庄市",
                                childs:[
                                         {
                                            id:"200100",
                                            text:"A区"
                                          },
                                          {
                                            id:"200101",
                                            text:"B区"
                                           }
                                        ]
                              },       
                              {
                                 id:"2002",
                                 text:"保定市",
                                 childs:[
                                          {
                                            id:"200200",
                                            text:"A区"
                                           },
                                           {
                                             id:"200201",
                                             text:"B区"
                                           }
                                        ]        
                              }
                            ]
                 }
               ]   ;