// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class AppSessionRequest;
@class AppSessionRequest_Builder;
@class AppSessionResponse;
@class AppSessionResponse_Builder;
@class SessionFile;
@class SessionFileItem;
@class SessionFileItem_Builder;
@class SessionFile_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface AppSessionBoardRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface AppSessionRequest : PBGeneratedMessage {
@private
  BOOL hasSequence_:1;
  BOOL hasRequestMapping_:1;
  BOOL hasContent_:1;
  BOOL hasAuthToken_:1;
  NSString* sequence;
  NSString* requestMapping;
  NSString* content;
  NSString* authToken;
  PBAppendableArray * sessionFilesArray;
}
- (BOOL) hasSequence;
- (BOOL) hasRequestMapping;
- (BOOL) hasContent;
- (BOOL) hasAuthToken;
@property (readonly, retain) NSString* sequence;
@property (readonly, retain) NSString* requestMapping;
@property (readonly, retain) NSString* content;
@property (readonly, retain) PBArray * sessionFiles;
@property (readonly, retain) NSString* authToken;
- (SessionFile*)sessionFilesAtIndex:(NSUInteger)index;

+ (AppSessionRequest*) defaultInstance;
- (AppSessionRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AppSessionRequest_Builder*) builder;
+ (AppSessionRequest_Builder*) builder;
+ (AppSessionRequest_Builder*) builderWithPrototype:(AppSessionRequest*) prototype;
- (AppSessionRequest_Builder*) toBuilder;

+ (AppSessionRequest*) parseFromData:(NSData*) data;
+ (AppSessionRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AppSessionRequest*) parseFromInputStream:(NSInputStream*) input;
+ (AppSessionRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AppSessionRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (AppSessionRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AppSessionRequest_Builder : PBGeneratedMessage_Builder {
@private
  AppSessionRequest* result;
}

- (AppSessionRequest*) defaultInstance;

- (AppSessionRequest_Builder*) clear;
- (AppSessionRequest_Builder*) clone;

- (AppSessionRequest*) build;
- (AppSessionRequest*) buildPartial;

- (AppSessionRequest_Builder*) mergeFrom:(AppSessionRequest*) other;
- (AppSessionRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AppSessionRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSequence;
- (NSString*) sequence;
- (AppSessionRequest_Builder*) setSequence:(NSString*) value;
- (AppSessionRequest_Builder*) clearSequence;

- (BOOL) hasRequestMapping;
- (NSString*) requestMapping;
- (AppSessionRequest_Builder*) setRequestMapping:(NSString*) value;
- (AppSessionRequest_Builder*) clearRequestMapping;

- (BOOL) hasContent;
- (NSString*) content;
- (AppSessionRequest_Builder*) setContent:(NSString*) value;
- (AppSessionRequest_Builder*) clearContent;

- (PBAppendableArray *)sessionFiles;
- (SessionFile*)sessionFilesAtIndex:(NSUInteger)index;
- (AppSessionRequest_Builder *)addSessionFiles:(SessionFile*)value;
- (AppSessionRequest_Builder *)setSessionFilesArray:(NSArray *)array;
- (AppSessionRequest_Builder *)setSessionFilesValues:(const SessionFile* *)values count:(NSUInteger)count;
- (AppSessionRequest_Builder *)clearSessionFiles;

- (BOOL) hasAuthToken;
- (NSString*) authToken;
- (AppSessionRequest_Builder*) setAuthToken:(NSString*) value;
- (AppSessionRequest_Builder*) clearAuthToken;
@end

@interface SessionFile : PBGeneratedMessage {
@private
  BOOL hasFieldName_:1;
  NSString* fieldName;
  PBAppendableArray * itemsArray;
}
- (BOOL) hasFieldName;
@property (readonly, retain) NSString* fieldName;
@property (readonly, retain) PBArray * items;
- (SessionFileItem*)itemsAtIndex:(NSUInteger)index;

+ (SessionFile*) defaultInstance;
- (SessionFile*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SessionFile_Builder*) builder;
+ (SessionFile_Builder*) builder;
+ (SessionFile_Builder*) builderWithPrototype:(SessionFile*) prototype;
- (SessionFile_Builder*) toBuilder;

+ (SessionFile*) parseFromData:(NSData*) data;
+ (SessionFile*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SessionFile*) parseFromInputStream:(NSInputStream*) input;
+ (SessionFile*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SessionFile*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SessionFile*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SessionFile_Builder : PBGeneratedMessage_Builder {
@private
  SessionFile* result;
}

- (SessionFile*) defaultInstance;

- (SessionFile_Builder*) clear;
- (SessionFile_Builder*) clone;

- (SessionFile*) build;
- (SessionFile*) buildPartial;

- (SessionFile_Builder*) mergeFrom:(SessionFile*) other;
- (SessionFile_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SessionFile_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasFieldName;
- (NSString*) fieldName;
- (SessionFile_Builder*) setFieldName:(NSString*) value;
- (SessionFile_Builder*) clearFieldName;

- (PBAppendableArray *)items;
- (SessionFileItem*)itemsAtIndex:(NSUInteger)index;
- (SessionFile_Builder *)addItems:(SessionFileItem*)value;
- (SessionFile_Builder *)setItemsArray:(NSArray *)array;
- (SessionFile_Builder *)setItemsValues:(const SessionFileItem* *)values count:(NSUInteger)count;
- (SessionFile_Builder *)clearItems;
@end

@interface SessionFileItem : PBGeneratedMessage {
@private
  BOOL hasType_:1;
  BOOL hasFile_:1;
  NSString* type;
  NSData* file;
}
- (BOOL) hasType;
- (BOOL) hasFile;
@property (readonly, retain) NSString* type;
@property (readonly, retain) NSData* file;

+ (SessionFileItem*) defaultInstance;
- (SessionFileItem*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SessionFileItem_Builder*) builder;
+ (SessionFileItem_Builder*) builder;
+ (SessionFileItem_Builder*) builderWithPrototype:(SessionFileItem*) prototype;
- (SessionFileItem_Builder*) toBuilder;

+ (SessionFileItem*) parseFromData:(NSData*) data;
+ (SessionFileItem*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SessionFileItem*) parseFromInputStream:(NSInputStream*) input;
+ (SessionFileItem*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SessionFileItem*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SessionFileItem*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SessionFileItem_Builder : PBGeneratedMessage_Builder {
@private
  SessionFileItem* result;
}

- (SessionFileItem*) defaultInstance;

- (SessionFileItem_Builder*) clear;
- (SessionFileItem_Builder*) clone;

- (SessionFileItem*) build;
- (SessionFileItem*) buildPartial;

- (SessionFileItem_Builder*) mergeFrom:(SessionFileItem*) other;
- (SessionFileItem_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SessionFileItem_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasType;
- (NSString*) type;
- (SessionFileItem_Builder*) setType:(NSString*) value;
- (SessionFileItem_Builder*) clearType;

- (BOOL) hasFile;
- (NSData*) file;
- (SessionFileItem_Builder*) setFile:(NSData*) value;
- (SessionFileItem_Builder*) clearFile;
@end

@interface AppSessionResponse : PBGeneratedMessage {
@private
  BOOL hasSequence_:1;
  BOOL hasRequestMapping_:1;
  BOOL hasResponseCode_:1;
  BOOL hasResponseResult_:1;
  NSString* sequence;
  NSString* requestMapping;
  NSString* responseCode;
  NSString* responseResult;
}
- (BOOL) hasSequence;
- (BOOL) hasRequestMapping;
- (BOOL) hasResponseCode;
- (BOOL) hasResponseResult;
@property (readonly, retain) NSString* sequence;
@property (readonly, retain) NSString* requestMapping;
@property (readonly, retain) NSString* responseCode;
@property (readonly, retain) NSString* responseResult;

+ (AppSessionResponse*) defaultInstance;
- (AppSessionResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AppSessionResponse_Builder*) builder;
+ (AppSessionResponse_Builder*) builder;
+ (AppSessionResponse_Builder*) builderWithPrototype:(AppSessionResponse*) prototype;
- (AppSessionResponse_Builder*) toBuilder;

+ (AppSessionResponse*) parseFromData:(NSData*) data;
+ (AppSessionResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AppSessionResponse*) parseFromInputStream:(NSInputStream*) input;
+ (AppSessionResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AppSessionResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (AppSessionResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AppSessionResponse_Builder : PBGeneratedMessage_Builder {
@private
  AppSessionResponse* result;
}

- (AppSessionResponse*) defaultInstance;

- (AppSessionResponse_Builder*) clear;
- (AppSessionResponse_Builder*) clone;

- (AppSessionResponse*) build;
- (AppSessionResponse*) buildPartial;

- (AppSessionResponse_Builder*) mergeFrom:(AppSessionResponse*) other;
- (AppSessionResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AppSessionResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSequence;
- (NSString*) sequence;
- (AppSessionResponse_Builder*) setSequence:(NSString*) value;
- (AppSessionResponse_Builder*) clearSequence;

- (BOOL) hasRequestMapping;
- (NSString*) requestMapping;
- (AppSessionResponse_Builder*) setRequestMapping:(NSString*) value;
- (AppSessionResponse_Builder*) clearRequestMapping;

- (BOOL) hasResponseCode;
- (NSString*) responseCode;
- (AppSessionResponse_Builder*) setResponseCode:(NSString*) value;
- (AppSessionResponse_Builder*) clearResponseCode;

- (BOOL) hasResponseResult;
- (NSString*) responseResult;
- (AppSessionResponse_Builder*) setResponseResult:(NSString*) value;
- (AppSessionResponse_Builder*) clearResponseResult;
@end

