platform :ios,'8.0'
target 'HybridApp' do
	pod 'MJExtension','3.0.13'
	pod 'MJRefresh','3.1.15.1'
	pod 'MBProgressHUD','1.1.0'
	pod 'PGDatePicker','1.5.12'
	pod 'SDWebImage','4.2.2'
	pod 'BaiduMapKit','3.4.2'
	pod 'Reachability','3.2'
	pod 'ASIHTTPRequest','1.8.2'
	pod 'Bugly','2.5.0'
        pod 'FMDB','2.7.2'

	project 'HybridApp/HybridApp.xcodeproj'

end

